---
provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  piedpiper-cppcheck-function:
    lang: python3-flask
    handler: ./piedpiper-cppcheck-function
    image: piedpiper-cppcheck-function:latest
